### PR TITLE
fixes #452

### LINKED ISSUE #452: ValueError in Labels issues?
has anyone ever come into the issue below when trying to test other SAM models:
Traceback (most recent call last):
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 145, in <module>
    main(args)
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 83, in main
    labels = [
  File "E:\PythonProjects\Grounded-Segment-Anything\EfficientSAM\grounded_mobile_sam.py", line 83, in <listcomp>
    labels = [
ValueError: too many values to unpack (expected 5)

Let me know how to fix this please. Thank you!

### PR DESCRIPTION
**Pull request by jmtatsch**

### CODE REVIEW

**Comment by rentainhe** [comment]
We will check this issue later

**Comment by rentainhe** [comment]
Hello, we've realized there're something change in the return results of grounding-dino code, maybe you can fix the conflicts and we will merge your PR as soon as possible

**Comment by rentainhe** [comment]
Thank u so much for fixing this issue!

**Comment by jmtatsch** [comment]
Thank u for advancing scene understanding and open sourcing it 🤠

**Pull request merged**
