### PR TITLE
Add support for Azure OpenAI, Palm, Replicate, Sagemaker (100+LLMs) - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@rentainhe can you take a look at this PR when you get the chance?

Happy to add more docs/testing if this initial commit looks good😊

**Comment by rentainhe** [comment]
This PR looks very nice. Would you be willing to add more judgment conditions and documentation? If users have not installed light-llm, they can use the original API provided by OpenAI.  @ishaan-jaff

**Comment by ishaan-jaff** [comment]
yes @rentainhe 

can you provide some guidance on what changes you'd like me to add ?

**Comment by rentainhe** [comment]
> yes @rentainhe
> 
> can you provide some guidance on what changes you'd like me to add ?

Hello! Maybe you can try to use:

```python
try:
    import lightllm
    HAS_LIGHTLLM = True
except:
    HAS_LIGHTLLM = False
```

Try to use a flag to control it, which may be better for the users who did not install `lightllm`, they can use openai original API instead of it

**Comment by rentainhe** [comment]
It would be very nice for u to add more documentation (maybe in README) about this update! You can try to update the `requirements.txt` to inform the users to install `litellm`

**Pull request merged**
