### PR TITLE
support multiple comma-separated text prompts for grounded sam demo

### PR DESCRIPTION
**Pull request by klarrieu**
Made a small change to support multiple comma-separated text prompts in the grounded sam demo.

Here is an example running the script with `--text-prompt "bear, gravel"`

grounded_sam_output.jpg
grounded_sam_output

mask_bear.jpg
mask_bear

mask_gravel.jpg
mask_gravel

Here is another example running the script with `--text-prompt "rock, boat"`

grounded_sam_output

### CODE REVIEW

**Comment by klarrieu** [comment]
Here is an example running the script with `--text-prompt "rock, boat"`

grounded_sam_output

**Comment by rentainhe** [comment]
Nice work~ we will review this today~ thanks for your contribution!

**Comment by SlongLiu** [comment]
Thanks for your PR. We suggest separating names with `.` for multiple objects, resulting in better performance. The comma may make the sentence ambiguous.

**Comment by klarrieu** [comment]
Thanks for the feedback. I made the requested change.

**Review by pierizvi — APPROVED** [review]
Looking good to close

**Comment by klarrieu** [comment]
@SlongLiu  My apologies, I didn't realize that functionality was already present in Grounding DINO. Then yes, we can close this PR, though I might suggest mentioning the multiple text prompt ability in the readme for this repository as well. Thanks for your time!

**Pull request closed without merging**
