### PR TITLE
Accelerate Image Annotation with SAM and Grounding DINO YouTube video and Google Colab

### PR DESCRIPTION
**Pull request by SkalskiP**
Hi, team 👋🏻! Today we released a new Youtube video along with a related Google Colab:
- https://youtu.be/oEQYStnF2l8
- https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/automated-dataset-annotation-and-evaluation-with-grounding-dino-and-sam.ipynb

I thought it could be cool to add them to README.md. I hope you'll agree :)

### CODE REVIEW

**Comment by rentainhe** [comment]
Thank you so much for this video!!!!!!

**Comment by rentainhe** [comment]
We will especially highlight this colab and your video!!!!!

**Review by rentainhe — APPROVED** [review]

**Comment by rentainhe** [comment]
We only keep your video as the Youtube video in the start of our readme and we specially highlight your tutorial which is really amazing! 
image

@SkalskiP

**Comment by SkalskiP** [comment]
Thank you very much for such a positive feedback! 🙏🏻 And thank you very much for adding our tutorial to README :) It was a pleasure to work with that project :)

**Pull request merged**
